In [57]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.datasets import fetch_20newsgroups
from sklearn.decomposition import NMF, LatentDirichletAllocation

n_docs = 10
def display_topics(model, feature_names, no_top_words,documents,ids,tfidf):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic {0}:".format(topic_idx))
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))
        foo = nmf.transform(tfidf)
        top_doc_indices = np.argsort( foo[:,topic_idx] )[::-1][0:n_docs]
        print(top_doc_indices)
        for doc_index in top_doc_indices:
            print(ids[doc_index])

#dataset = fetch_20newsgroups(shuffle=True, random_state=1, remove=('headers', 'footers', 'quotes'))
#documents = dataset.data
all_tweets = pd.read_csv('train_tweets.csv')
i=18

sources = all_tweets['source'].unique().tolist()
source= sources[i]
print(source)
topic_tweets = all_tweets[all_tweets['source']==source]['text'].tolist()
documents = topic_tweets
ids = all_tweets[all_tweets['source']==source]['class_label'].tolist()

no_features = 1000

# NMF is able to use tf-idf
tfidf_vectorizer = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
tfidf = tfidf_vectorizer.fit_transform(documents)
tfidf_feature_names = tfidf_vectorizer.get_feature_names()

# LDA can only use raw term counts for LDA because it is a probabilistic graphical model
#tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2,  stop_words='english')
#tf = tf_vectorizer.fit_transform(documents)
#tf_feature_names = tf_vectorizer.get_feature_names()

no_topics = 10

# Run NMF
nmf = NMF(n_components=no_topics, random_state=1, alpha=.1, l1_ratio=.5, init='nndsvd').fit(tfidf)
n_top_documents = 5
n_top_words = 5
# get list of feature names
feature_names = tfidf_vectorizer.get_feature_names()
#for topic_id, topic in enumerate(nmf.components_):
        #word_list = []
        #for i in topic.argsort()[:-n_top_words - 1:-1]:
        #    word_list.append(feature_names[i])
            

            # check that the review contains one of the topic words
            #if any(word in df['reviewText'].iloc[doc_index].lower() for word in topic_words):

# Run LDA
#lda = LatentDirichletAllocation(n_topics=no_topics, max_iter=5, learning_method='online', learning_offset=50.,random_state=0).fit(tf)

no_top_words = 5
display_topics(nmf, tfidf_feature_names, no_top_words,documents,ids,tfidf)
#display_topics(lda, tf_feature_names, no_top_words)



@@NikeSupport
Topic 0:
run club nike app facebook
[66 31 69 11 40 30 23 50  1 33]
1
1
1
1
1
1
1
1
1
1
Topic 1:
fans listen return power weeks
[25 49 60  9 24 20 21 22 23 72]
1
1
1
1
1
1
1
1
1
1
Topic 2:
la en que el puedo
[70 12 39 21 47 41  5 58 30 36]
1
1
1
1
1
1
1
1
1
1
Topic 3:
hey new nike like donating
[53 42  3 63 16  6 23 69  2 72]
1
1
1
1
1
1
1
1
1
1
Topic 4:
nrc mail trocar app distance
[ 8 29 16  6 62 21 68 48 26 14]
1
1
1
1
1
1
1
1
1
1
Topic 5:
need couldn fix don team
[ 0 19 38 57 34 35  6  5 33 32]
1
1
1
1
1
1
1
1
1
1
Topic 6:
today help think ago bought
[ 2 37 13 32 26 72 33 22 61 68]
1
1
1
1
1
1
1
1
1
1
Topic 7:
power return cats like looks
[65  9 24 55 60 49 33 54 63 34]
1
1
1
1
1
1
1
1
1
1
Topic 8:
shoes marathon release think weeks
[59 22 34 48 13  2 72 24 21 23]
1
1
1
1
1
1
1
1
1
1
Topic 9:
air nike just hey service
[27 45  3 71 21 10 54 66 35 26]
1
1
1
1
1
1
1
1
1
1


In [55]:
all_tweets.columns

Index(['Unnamed: 0', 'choose_one', 'class_label', 'mentions', 'source',
       'text'],
      dtype='object')

In [ ]:
from textblob import TextBlob
sentiment = []
for tweet in train_tweets['text']:
    
     # create TextBlob object of passed tweet text 
    analysis = TextBlob(tweet)
    tweetiment = analysis.sentiment.polarity
        # set sentiment 
    #if analysis.sentiment.polarity > 0: 
    #    tweetiment =  'positive'
    #elif analysis.sentiment.polarity == 0: 
    #    tweetiment = 'neutral'
    #else: 
    #    tweetiment = 'negative'
    sentiment.append(tweetiment)
train_tweets['sentiment'] = sentiment